##
## Copyright (c) 2023 VIDAL & ASTUDILLO Ltda and others.
##
## This program and the accompanying materials are made available under the
## terms of the MIT License which accompanies this distribution, and is 
## available at:
## https://github.com/vidalastudillo/provision_pi/blob/main/LICENSE
##


version: '3.5'

services:
  provision_pi:
    container_name: ${PI_PROJECT_NAME:?No project name set}_provision_pi
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ${PI_BASE_FILE_NAME}.Dockerfile
      args:
        PI_USERNAME: ${PI_USERNAME?No username set}
        PI_PASSWORD: ${PI_PASSWORD}
        PI_HOST_PUID: ${PI_HOST_PUID}
        PI_HOST_PGID: ${PI_HOST_PGID}
    cap_add:
      - SYS_PTRACE  # To allow strace to debug access problems
    hostname: provision_pi.local
    networks:
      - provision_pi
    environment:
      - PUID=${PI_HOST_PUID}
      - PGID=${PI_HOST_PGID}
      - TZ=${PI_TIMEZONE}
    device_cgroup_rules:
      - 'c ${PI_DRIVER_MAJOR_VERSION}:* rmw'  # To enable access to the Pi Driver
    volumes:
      - ${PI_HOST_DATA_PATH?No data path set}/${PI_USERNAME?No username set}:/home/${PI_USERNAME?No username set}  # The user home is considered persistent data
      - /dev:/dev  # To mount /bus/usb and /sd* folders 
      - /run/udev:/run/udev:ro  # udev information

networks:
  provision_pi:
    name: ${PI_PROJECT_NAME}_provision_pi
